[Version]
Class=IEXPRESS
SEDVersion=3
[Options]
PackagePurpose=ExtractOnly
ShowInstallProgramWindow=0
HideExtractAnimation=0
UseLongFileName=1
InsideCompressed=0
CAB_FixedSize=0
CAB_ResvCodeSigning=0
RebootMode=I
InstallPrompt=%InstallPrompt%
DisplayLicense=%DisplayLicense%
FinishMessage=%FinishMessage%
TargetName=%TargetName%
FriendlyName=%FriendlyName%
AppLaunched=%AppLaunched%
PostInstallCmd=%PostInstallCmd%
AdminQuietInstCmd=%AdminQuietInstCmd%
UserQuietInstCmd=%UserQuietInstCmd%
SourceFiles=SourceFiles
[Strings]
InstallPrompt=Would You Like To Install Soup?
DisplayLicense=
FinishMessage=Thank you for Installing Soup!
TargetName=C:\Users\amigala\Desktop\Github\Soup\Test Files\Installer.EXE
FriendlyName=Soup Installer
AppLaunched=
PostInstallCmd=
AdminQuietInstCmd=
UserQuietInstCmd=
FILE0="Soup.bat"
[SourceFiles]
SourceFiles0=C:\Users\amigala\Desktop\Github\Soup\Test Files\
[SourceFiles0]
%FILE0%=
